import ItemStructure from "./ItemStructure";
const item_list: ItemStructure[] = [
  {
    id: 1,
    name: "ULTRABOOST",
    color: "red",
    brand: "adidas",
    gender: "male",
    price: 250,
    discount: 0.5,
  },
  {
    id: 2,
    name: "ULTRABOOST",
    color: "red",
    brand: "adidas",
    gender: "male",
    price: 250,
    discount: 0.5,
  },
  {
    id: 3,
    name: "NMD",
    color: "blue",
    brand: "adidas",
    gender: "male",
    price: 150,
    discount: 0.5,
  },
  {
    id: 4,
    name: "EQT",
    color: "blue",
    brand: "adidas",
    gender: "male",
    price: 250,
    discount: 0.5,
  },
  {
    id: 5,
    name: "AIR MAX",
    color: "black",
    brand: "nike",
    gender: "female",
    price: 350,
    discount: 0.5,
  },
  {
    id: 6,
    name: "AIR FORCE 1",
    color: "black",
    brand: "nike",
    gender: "female",
    price: 150,
    discount: 0.5,
  },
  {
    id: 7,
    name: "NMD",
    color: "black",
    brand: "adidas",
    gender: "female",
    price: 200,
    discount: 0.5,
  },
  {
    id: 8,
    name: "ULTRABOOST",
    color: "red",
    brand: "adidas",
    gender: "female",
    price: 200,
    discount: 0.5,
  },
  {
    id: 9,
    name: "EQT",
    color: "white",
    brand: "adidas",
    gender: "male",
    price: 150,
    discount: 0.5,
  },
  {
    id: 10,
    name: "PUMA",
    color: "white",
    brand: "puma",
    gender: "male",
    price: 100,
    discount: 0.5,
  },
];

export default item_list;
